### ISSUE TITLE
Move TARGET_USERNAME to json or txt file

### ISSUE THREAD

**Issue by fzn0x** [2pai/instastory-monitor-telegram#14]
I used the target username in .env and it doesn't look neat, maybe we can use the json or txt file.

**Comment by 2pai** [comment]
Hmm, I don't think so. 

Can you elaborate more on why we have to move the target_username to the JSON file?

Right now we're using ENV the TARGET_USERNAME simply just a string with comma-separated. 
It's easier for us to set up using the ENV by `export TARGET_USERNAME = 'xxx,xxx'` rather than create a new file. 

Here's the example case when running using Github Actions

![image](https://user-images.githubusercontent.com/22183588/111902592-ccb02c00-8a70-11eb-86ef-eb7a027f1b5e.png)

**Comment by fzn0x** [comment]
> Hmm, I don't think so.
> 
> Can you elaborate more on why we have to move the target_username to the JSON file?
> 
> Right now we're using ENV the TARGET_USERNAME simply just a string with comma-separated.
> It's easier for us to set up using the ENV by `export TARGET_USERNAME = 'xxx,xxx'` rather than create a new file.
> 
> Here's the example case when running using Github Actions
> 
> ![image](https://user-images.githubusercontent.com/22183588/111902592-ccb02c00-8a70-11eb-86ef-eb7a027f1b5e.png)

maybe some people are not familiar with the long value in .env but I see from the screenshot above it looks like .env is a good choice, case closed.
